spring:
  datasource:
    url: jdbc:mysql://localhost:3306/motioncare_appointments?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: motioncare
    password: motioncare123
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  # Liquibase configuration
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  # JPA/Hibernate configuration (if needed in future)
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

# MyBatis configuration
mybatis:
  type-aliases-package: com.motioncare.appointments.model,com.motioncare.user.model
  configuration:
    map-underscore-to-camel-case: true

# Logging
logging:
  level:
    org.springframework.jdbc: DEBUG
    liquibase: INFO
